[package]
name = "cooper"
version = "0.1.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/cooper-rs"
homepage = "https://github.com/fpagliughi/cooper-rs"
license = "MIT"
readme = "README.md"
keywords = ["actors", "futures"]
categories = ["asynchronous", "concurrency"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
#tokio-core = "0.1"
#tokio-io = "0.1"

