[package]
name = "cooper"
version = "0.1.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/cooper-rs"
homepage = "https://github.com/fpagliughi/cooper-rs"
license = "MIT"
edition = "2018"
readme = "README.md"
keywords = ["actors", "futures"]
categories = ["asynchronous", "concurrency"]
description = """
A simple, in-process, async Actor library for Rust.
"""

[dependencies]
futures = "0.3"
smol = "1.2"


